---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: default
  run_list: ["recipe[ossec]"]
  attributes: {}
- name: wui
  provisioner:
    name: chef_zero
  driver_config:
    network:
      - ["private_network", {ip: "192.168.33.33"}]
  run_list:
    - "recipe[ossec::server]"
    - "recipe[ossec::wui]"
  attributes:
    dev_mode: true
  data_bags_path: 'test/integration/default/data_bags'
- name: purge
  run_list:
    - "recipe[ossec]"
    - "recipe[ossec::purge]"
    - "recipe[ossec::purge]"
- name: purge_from_clean
  run_list:
    - "recipe[ossec::purge]"
    - "recipe[ossec::purge]"